import { Student } from "/Users/tbagggg/Downloads/Chapter5Homework/students";

let student1 = new Student("Tristan", "lux", 19, 1, "tristan.lux8@gmail.com", "7 Weir St, Branford, CT")
let student2 = new Student("John", "Doe", 11, 2, "johndoe@gmail.com", "77 Near St, West Haven, CT")

console.log(student1)
student1.setFirstName("T.")
student1.setLastName("L.")
student1.setID(1)
student1.setEnrolledCourses(5)
student1.setEmailAddress("tristanlux@icloud.com")
student1.setHomeAddress("7 W. S. Bran. CT")
console.log("SET METHODS HAVE BEEN USED\n")
console.log(student1)
console.log("\n\n")

console.log(student2)
student2.setFirstName("J.")
student2.setLastName("D.")
student2.setID(2)
student2.setEnrolledCourses(6)
student2.setEmailAddress("JohnDoe@icloud.com")
student2.setHomeAddress("77 N. S. WestHav. CT")
console.log("SET METHODS HAVE BEEN USED\n")
console.log(student2)